import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToggleDemo } from "@/components/DarkModeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import Header from "@/components/Header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yoel Weisberg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black bg-white`}
      >
        {/* Navigation */}
        <Header />
        {children}
      </body>
    </html>
  );
}
