import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Header from "@/components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { DataProvider } from "./context/DataContext";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yoel Weisberg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DataProvider>
        <UserProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black bg-white`}
          >
            {/* Navigation */}
            <Header />
            {children}
          </body>
        </UserProvider>
      </DataProvider>
    </html>
  );
}
